Description: To make cloudformation be able to deploy with a Gitlab runner in AWS.

Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - Label: 
          default: "Gitlab runner"
        Parameters: 
          - GitlabRunnerAccount          
          - GitlabRunnerRoleName

    ParameterLabels:
      GitlabRunnerAccount:
        default: "What is the Account number of the AWS account the Gitlab runner is running in?"
      GitlabRunnerRoleName:
        default: "What is the name of the IAM role for Gitlab runner host?"

Parameters:
    GitlabRunnerAccount:
      Type: String
      Description: The account where the Gitlab runner is. In AWS console click Support->Support Center. Account number.
  
    GitlabRunnerRoleName:
      Type: String
      Description: The Gitlab runner role name in AWS. Tip. Go to https://console.aws.amazon.com/iam/home#/roles and search for "GitlabRunnerRole". Example. For the Role ARN arn:aws:iam::1234567890987:role/gitlab-runner-GitlabRunnerRole the name to use is "gitlab-runner-GitlabRunnerRole"
      Default: gitlab-runner-GitlabRunnerRole
      AllowedPattern: ([^:]+)
      ConstraintDescription: Must be role name, e.g. not the complete ARN.

Resources:
  DeployRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Sub ${AWS::StackName}-DeployRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${GitlabRunnerAccount}:role/${GitlabRunnerRoleName}
            Action: sts:AssumeRole  
      ManagedPolicyArns:    
      - !Ref DeployPolicy

  DeployPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub ${AWS::StackName}-DeployPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - cloudformation:ValidateTemplate
              - cloudformation:CreateStack
              - cloudformation:DescribeStacks
              - ecs:DescribeClusters
              - ecs:CreateCluster
            Resource: "*"
            
Outputs:
  DeployRole:
    Description: Role to deploy cloudformation
    Value: !GetAtt DeployRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-DeployRole